### PR TITLE
Add FileTest::size method

### PR DESCRIPTION
**Pull request by radeksimko**
I don't see any reason to leave out this method, the code I'm trying to test is using it and I'm having troubles covering this code with tests.

To be very specific, I'm trying to test Homebrew Cask code which then calls Homebrew itself and ends up here:
https://github.com/Homebrew/homebrew/blob/bc0c203934f67624a4a3cd2bd15f1b4eb93b0236/Library/Homebrew/download_strategy.rb#L242-244

on following error:
```
NoMethodError:
       undefined method `size?' for FakeFS::FileTest:Module
```

Tests will fail with the code currently on `HEAD`, but pass after merging #268

### CODE REVIEW

**Comment by radeksimko** [comment]
Any chance on getting this merged or at least getting any feedback?
cc @defunkt @smtlaissezfaire @eventualbuddha @jfirebaugh

**Comment by smtlaissezfaire** [comment]
Seems ok to me.  I'll look to merge it tonight.

**Comment by smtlaissezfaire** [comment]
Released 0.6.1 with this fix.

**Comment by radeksimko** [comment]
@smtlaissezfaire Thanks Scott, but I don't see the new release:

https://github.com/defunkt/fakefs/tags

```
$ master > git pull origin master
From github.com:defunkt/fakefs
 * branch            master     -> FETCH_HEAD
Already up-to-date.
$ master > git tag -l | tail
v0.4.0
v0.4.1
v0.4.2
v0.4.3
v0.5.0
v0.5.1
v0.5.2
v0.5.3
v0.5.4
v0.6.0
```

**Comment by radeksimko** [comment]
Ah, it seems that Rubygems pick it up even thought it's not tagged...
https://rubygems.org/gems/fakefs

**Comment by smtlaissezfaire** [comment]
Yeah, it just hasn't been tagged in the repo.  I need to add something automatic in the rakefile to tag it
